# Generated by Django 5.1.4 on 2025-02-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangoexport',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mangoexport',
            name='variety',
            field=models.CharField(max_length=100),
        ),
    ]
