# Generated by Django 5.1.4 on 2025-02-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0002_alter_mangoexport_order_id_alter_mangoexport_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangoexport',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
    ]
