# Generated by Django 5.1.4 on 2025-02-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0003_alter_mangoexport_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangoexport',
            name='id',
        ),
        migrations.AlterField(
            model_name='mangoexport',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
