# Generated by Django 5.1.4 on 2025-02-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mango', '0004_remove_mangoexport_id_alter_mangoexport_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangoexport',
            options={'ordering': ['order_id']},
        ),
        migrations.AlterField(
            model_name='mangoexport',
            name='variety',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
